### ISSUE TITLE
The library soft_renderer

### ISSUE THREAD

**Issue by Linxu59** [jadewu/3D-Human-Face-Reconstruction-with-3DMM-face-model-from-RGB-image#1]
Hi, the library installed from Soft Rasterizer doesn't contain SoftRenderer function. Is this function be removed?

**Comment by jadewu** [comment]
Yes, this function and its file were removed last month by the author. The function SoftRasterizer is in use. We could find how to implement it now in example files, demo_deform and demo_renderer.
